# Configuration for https://goreleaser.com/
project_name: authenticator

builds:
  - id: aws-iam-authenticator
    binary: aws-iam-authenticator
    main: ./cmd/aws-iam-authenticator/
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X pkg.Version={{.Version}} -X pkg.CommitID={{.Commit}} -buildid=''"

dockers:
  - ids:
     - aws-iam-authenticator
    dockerfile: Dockerfile.scratch
    goarch: arm64
    use_buildx: true
    image_templates:
     - "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}-arm64v8"
    build_flag_templates:
     - --platform=linux/arm64
     - --label=org.opencontainers.image.title={{ .ProjectName }}
     - --label=org.opencontainers.image.description={{ .ProjectName }}
     - --label=org.opencontainers.image.url=https://github.com/kronostechnologies/aws-iam-authenticator
     - --label=org.opencontainers.image.source=https://github.com/kronostechnologies/aws-iam-authenticator
     - --label=org.opencontainers.image.version={{ .Version }}
     - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - ids:
     - aws-iam-authenticator
    dockerfile: Dockerfile.scratch
    use_buildx: true
    image_templates:
     - "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}-amd64"
    build_flag_templates:
     - --platform=linux/amd64
     - --label=org.opencontainers.image.title={{ .ProjectName }}
     - --label=org.opencontainers.image.description={{ .ProjectName }}
     - --label=org.opencontainers.image.url=https://github.com/kronostechnologies/aws-iam-authenticator
     - --label=org.opencontainers.image.source=https://github.com/kronostechnologies/aws-iam-authenticator
     - --label=org.opencontainers.image.version={{ .Version }}
     - --label=org.opencontainers.image.revision={{ .FullCommit }}


docker_manifests:
  - name_template: "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}"
    image_templates:
     - "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}-amd64"
     - "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}-arm64v8"


snapshot:
  name_template: "git-{{.ShortCommit}}"

archives:
  - id: bin
    format: binary

